name: 'ESLint Test'
description: 'Run ESLint on files changed in a pull request with inline error and warning annotations'
author: 'AbdulRehman-1'

branding:
  icon: 'check-square'
  color: 'red'

runs:
  using: 'node16'
  main: 'dist/index.js'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    required: false
    default: ${{ github.token }}
  eslint-args:
    description: 'ESLint CLI flags'
    required: false
    default: ''
  eslintrc:
    description: "User's eslintrc file"
    required: false
    default: false
  extensions:
    description: 'Extensions to filter'
    required: false
    default: 'js'
  annotations:
    description: 'Enable or disable annotations'
    required: false
    default: true
  auto-fix-before-test:
    description: 'Auto format and fix lint issues that are fixable by --fix before actual testing'
    required: false
    default: true
  bin-path:
    description: 'Path to eslint installation directory. Defaults to `node_modules/eslint/bin`'
    required: false
    default: 'node_modules/eslint/bin'
