name: Lint

env:
  NODE_VERSION: 16

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: node --version
      - run: npm --version

      - run: npm ci
      - run: npm ls --depth=0

      - uses: ./
        with:
          extensions: 'js,ts'
